# Aplicacion 1
services:
- type: web
  name: app_webpy
  runtime: python
  repo: https://github.com/GRJR1325/aplicacion_web
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python3 web/app.py

- type: web
  name: api_rest
  runtime: python3.10
  repo: https://github.com/GRJR1325/api_rest
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT

databases:
- name: prueba_db
  databaseName: db_agenda_zdvl
  user: user
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"

version: "1"
